## datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb?&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    username: root
    password: team-2

  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
